import { Router } from "express";
import authRouter from "./auth.route.js";
import adminRouter from "./admin.route.js";
import productRouter from "./product.route.js";
import categoryRouter from "./category.route.js";
import cartRouter from "./cart.route.js";
import wishlistRouter from "./wishlist.route.js";
import addressRouter from "./address.route.js";
import orderRouter from "./order.route.js";
import customerRouter from "./customer.route.js";
import vendorRouter from "./vendor.route.js";
import storeRouter from "./store.route.js";
import inventoryRouter from "./inventory.route.js";
import couponRouter from "./coupon.route.js";
import uploadRouter from "./upload.route.js";
import notificationRouter from "./notification.route.js";
import paymentRouter from "./payment.route.js";
import reviewRouter from "./review.route.js";
import bannerRouter from "./banner.route.js";
import brandRouter from "./brand.route.js";

const router = Router();

router.use('/api/auth', authRouter);
router.use('/api/admin', adminRouter);
router.use('/api/admin/notifications', notificationRouter);
router.use('/api/vendors', vendorRouter);
router.use('/api/vendor', vendorRouter);
router.use('/api/stores', storeRouter);
router.use('/api/products', productRouter);
router.use('/api/inventory', inventoryRouter);
router.use('/api/coupons', couponRouter);
router.use('/api/uploads', uploadRouter);
router.use('/api/categories', categoryRouter);
router.use('/api/cart', cartRouter);
router.use('/api/wishlist', wishlistRouter);
router.use('/api/addresses', addressRouter);
router.use('/api/orders', orderRouter);
router.use('/api/customer', customerRouter);
router.use('/api/payment', paymentRouter);
router.use('/api/payments', paymentRouter);
router.use("/api/reviews", reviewRouter);
router.use("/api/banners", bannerRouter);
router.use("/api/admin/banners", bannerRouter);
router.use("/api/brands", brandRouter);
router.use("/api/admin/brands", brandRouter);

export default router;